### ISSUE TITLE
Setup CI with Azure Pipelines

### ISSUE THREAD

**Issue by utilForever** [utilForever/RosettaStone#145]
Azure Pipelines builds, tests, and deploys your code to any platform.
Add more parallel jobs for even faster pipelines.

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by utilForever** [comment]
@kaylangan Hi, I am configuring yml on Civilizationpp project (https://github.com/utilForever/Civilizationpp) using CMake. I have successfully built it on Ubuntu and macOS. But I'm having trouble setting up the Windows platform. Can I help you?

**Comment by kaylangan** [comment]
@utilForever I put up a PR over in that project that gets the Windows build going: https://github.com/utilForever/Civilizationpp/pull/24

**Comment by utilForever** [comment]
@kaylangan Hi, Can you take a look at this problem in ```azure``` branch?

```
2018-10-19T04:25:27.9630676Z ##[command]git submodule sync
2018-10-19T04:25:29.7325288Z ##[command]git -c http.https://github.com.extraheader="AUTHORIZATION: basic ***" submodule update --init --force --depth=2
2018-10-19T04:25:30.1042233Z Submodule 'Libraries/Clara' (https://github.com/catchorg/Clara) registered for path 'Libraries/Clara'
2018-10-19T04:25:30.1043603Z Submodule 'Libraries/better-enums' (https://github.com/aantron/better-enums) registered for path 'Libraries/better-enums'
2018-10-19T04:25:30.1044950Z Submodule 'Libraries/googletest' (https://github.com/google/googletest) registered for path 'Libraries/googletest'
2018-10-19T04:25:31.4568988Z Cloning into 'D:/a/1/s/Libraries/Clara'...
2018-10-19T04:25:32.0488526Z Cloning into 'D:/a/1/s/Libraries/better-enums'...
2018-10-19T04:25:32.9264396Z Cloning into 'D:/a/1/s/Libraries/googletest'...
2018-10-19T04:25:33.3204363Z Submodule path 'Libraries/Clara': checked out 'ba5485cb56329db3ea3f5402ef596d3b512b903a'
2018-10-19T04:25:34.4656796Z error: Server does not allow request for unadvertised object 2fad3f60eea97cf3b75339a1562ab13d5e0cc4f7
2018-10-19T04:25:34.5557907Z Fetched in submodule path 'Libraries/better-enums', but it did not contain 2fad3f60eea97cf3b75339a1562ab13d5e0cc4f7. Direct fetching of that commit failed.
2018-10-19T04:25:34.5920486Z ##[error]System.InvalidOperationException: Git submodule update failed with exit code: 1
   at Agent.Plugins.Repository.GitSourceProvider.<GetSourceAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.Plugins.Repository.CheckoutTask.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.PluginHost.Program.Main(String[] args)
2018-10-19T04:25:34.5959737Z ##[section]Finishing: Checkout
```
